"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Camera, CheckCircle2, ImagePlus, LocateFixed, QrCode, Trash2, TriangleAlert } from "lucide-react";
import { api } from "@/lib/api";
import { readSession } from "@/lib/session";
import type { BinColor, Profile, Submission } from "@/lib/types";

const bins: { type: BinColor; title: string; detail: string; required: boolean; color: string }[] = [
  { type: "GREEN", title: "Green bin", detail: "Wet and organic waste", required: true, color: "green" },
  { type: "BLUE", title: "Blue bin", detail: "Dry recyclables", required: true, color: "blue" },
  { type: "RED", title: "Red bin", detail: "Sanitary waste", required: true, color: "red" },
  { type: "BLACK", title: "Black bin", detail: "Hazardous waste", required: false, color: "black" }
];
type PhotoMap = Record<BinColor, File[]>;
const emptyPhotos = (): PhotoMap => ({ GREEN: [], BLUE: [], RED: [], BLACK: [] });

export function BinCapture() {
  const [profile, setProfile] = useState<Profile | null>(null); const [photos, setPhotos] = useState<PhotoMap>(emptyPhotos); const [location, setLocation] = useState<{ lat?: number; lng?: number; status: "loading" | "ready" | "unavailable" }>({ status: "loading" }); const [submitting, setSubmitting] = useState(false); const [result, setResult] = useState<Submission | null>(null); const [error, setError] = useState("");
  const requiredComplete = bins.filter(bin => bin.required).every(bin => photos[bin.type].length > 0);
  useEffect(() => { if (!readSession()) { window.location.assign("/"); return; } void api.profile().then(setProfile).catch(err => setError(err instanceof Error ? err.message : "Unable to load household.")); void refreshLocation(); }, []);
  async function refreshLocation() { setLocation({ status: "loading" }); if (!navigator.geolocation) { setLocation({ status: "unavailable" }); return; } navigator.geolocation.getCurrentPosition(({ coords }) => setLocation({ lat: coords.latitude, lng: coords.longitude, status: "ready" }), () => setLocation({ status: "unavailable" }), { enableHighAccuracy: true, timeout: 10000, maximumAge: 60000 }); }
  function addPhotos(type: BinColor, incoming: FileList | null) { if (!incoming) return; setPhotos(current => ({ ...current, [type]: [...current[type], ...Array.from(incoming)].slice(0, 2) })); }
  function removePhoto(type: BinColor, index: number) { setPhotos(current => ({ ...current, [type]: current[type].filter((_, itemIndex) => itemIndex !== index) })); }
  async function submit() { if (!profile?.householdId) { setError("Set up your household before checking your bins."); return; } if (!requiredComplete) { setError("Add at least one photo for your green, blue, and red bins."); return; } setSubmitting(true); setError(""); let latest = location; if (navigator.geolocation) { try { const coords = await new Promise<GeolocationCoordinates>((resolve, reject) => navigator.geolocation.getCurrentPosition(position => resolve(position.coords), reject, { enableHighAccuracy: true, timeout: 10000, maximumAge: 60000 })); latest = { lat: coords.latitude, lng: coords.longitude, status: "ready" }; setLocation(latest); } catch { /* Location warning remains visible and the API keeps the current coordinates. */ } } if (!latest.lat || !latest.lng) { setSubmitting(false); setError("Location is needed to confirm you are at your registered household."); return; } const body = new FormData(); body.append("householdId", String(profile.householdId)); body.append("lat", String(latest.lat)); body.append("lng", String(latest.lng)); bins.forEach(bin => photos[bin.type].forEach(photo => { body.append("binImages", photo); body.append("binTypes", bin.type); })); try { setResult(await api.submitBins(body)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to check your bins."); } finally { setSubmitting(false); } }
  const attempts = useMemo(() => result?.attemptNumber || 0, [result]);
  if (result) return <ResultScreen result={result} onRetry={() => { setResult(null); setPhotos(emptyPhotos()); }} />;
  return <main className="capture-page"><header className="capture-header"><Link href="/dashboard"><ArrowLeft />Dashboard</Link><div><span>Step 1</span><b>Photograph bins</b><i>Step 2 · AI analysis</i><i>Step 3 · Pickup pass</i></div></header><section className="capture-intro"><div><h1>Show us your bins, ready for pickup.</h1><p>Take one or two clear photos of each bin before the collection window.</p></div><p className={`location-status ${location.status}`}><LocateFixed />{location.status === "loading" ? "Getting your location..." : location.status === "ready" ? "Location ready" : "Location unavailable"}</p></section>{!profile?.householdId && <div className="capture-alert"><TriangleAlert />Set up your household on the dashboard before submitting a verification.</div>}<section className="bin-card-grid">{bins.map(bin => <BinCard key={bin.type} bin={bin} files={photos[bin.type]} onAdd={files => addPhotos(bin.type, files)} onRemove={index => removePhoto(bin.type, index)} />)}</section><section className="capture-actions"><div><strong>Daily verification</strong><p>{attempts ? `${attempts} of 3 attempts used today.` : "You can complete up to 3 verification attempts each day."}</p></div><button className="button-primary" disabled={submitting || !profile?.householdId} onClick={submit}>{submitting ? "Analysing bins..." : <><CheckCircle2 />Check my bins</>}</button></section>{error && <p className="capture-error" role="alert">{error}</p>}</main>;
}

function BinCard({ bin, files, onAdd, onRemove }: { bin: typeof bins[number]; files: File[]; onAdd: (files: FileList | null) => void; onRemove: (index: number) => void }) { return <article className={`bin-card ${bin.color}`}><header><span className="bin-symbol">♻</span><div><h2>{bin.title} {!bin.required && <small>Optional</small>}</h2><p>{bin.detail}</p></div><b>{files.length}/2</b></header><div className="photo-list">{files.map((file, index) => <PhotoPreview key={`${file.name}-${index}`} file={file} label={bin.title} onRemove={() => onRemove(index)} />)}{files.length < 2 && <label className="add-photo"><Camera /><span>Add photo</span><input type="file" accept="image/*" capture="environment" multiple onChange={event => onAdd(event.target.files)} /></label>}</div><small className="photo-hint">{files.length === 2 ? "Maximum 2 photos added" : bin.required ? "At least one photo required" : "Add a photo if you have hazardous waste"}</small></article>; }
function PhotoPreview({ file, label, onRemove }: { file: File; label: string; onRemove: () => void }) { const [src, setSrc] = useState(""); useEffect(() => { const url = URL.createObjectURL(file); setSrc(url); return () => URL.revokeObjectURL(url); }, [file]); return <div className="photo-preview"><img src={src} alt={`${label} preview`} /><button onClick={onRemove} aria-label={`Remove ${label} photo`}><Trash2 /></button></div>; }
function ResultScreen({ result, onRetry }: { result: Submission; onRetry: () => void }) { const approved = result.status === "APPROVED"; return <main className="result-page"><section className={`result-card ${result.status.toLowerCase()}`}><span>{approved ? <CheckCircle2 /> : <TriangleAlert />}</span><h1>{approved ? "Verification successful" : result.status === "PENDING_RETRY" ? "A quick update is needed" : "Verification not approved"}</h1><p>{approved ? "Your bins are ready for collection." : result.failureReason || "Review your bin photos and try again."}</p>{approved && result.qrCodeBase64 && <><img src={`data:image/png;base64,${result.qrCodeBase64}`} alt="Pickup QR pass" /><p className="qr-expiry"><QrCode />Valid until {formatDate(result.qrExpiresAt)}</p></>}<div className="bin-breakdown">{result.binResults.map(bin => <div key={bin.binType}><b className={bin.passed ? "pass" : "fail"}>{bin.passed ? "✓" : "!"}</b><span><strong>{bin.binType.toLowerCase()} bin</strong><small>{bin.contaminationDetail || `${Math.round(bin.aiConfidence * 100)}% confidence`}</small></span></div>)}</div><div className="result-actions">{approved ? <Link className="button-primary" href="/dashboard">Back to dashboard</Link> : <button className="button-primary" onClick={onRetry}>Try again</button>}</div></section></main>; }
function formatDate(value?: string | null) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "--"; }
