"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Camera, CircleAlert, Plus, Send } from "lucide-react";
import { api } from "@/lib/api";
import { readSession } from "@/lib/session";
import type { Complaint, Profile } from "@/lib/types";

export function GrievanceCenter() {
  const [profile, setProfile] = useState<Profile | null>(null); const [reports, setReports] = useState<Complaint[]>([]); const [creating, setCreating] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const refresh = async () => { try { const [nextProfile, nextReports] = await Promise.all([api.profile(), api.complaints()]); setProfile(nextProfile); setReports(nextReports); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load reports."); } };
  useEffect(() => { if (!readSession()) { window.location.assign("/"); return; } void refresh(); }, []);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile?.wardId) { setMessage("Your account needs a ward before you can report an issue."); return; } const form = new FormData(event.currentTarget); const image = form.get("image"); if (!(image instanceof File) || image.size === 0) { setMessage("Add a photo to help the collection team understand the issue."); return; } setLoading(true); setMessage(""); const payload = new FormData(); payload.append("image", image); payload.append("complaint", new Blob([JSON.stringify({ title: form.get("title"), description: form.get("description"), category: form.get("category"), wardId: profile.wardId })], { type: "application/json" })); try { await api.createComplaint(payload); setCreating(false); setMessage("Your report has been submitted."); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit report."); } finally { setLoading(false); } }
  return <main className="grievance-page"><header><Link href="/dashboard"><ArrowLeft />Dashboard</Link><div><h1>Grievances</h1><p>Track the issues you have reported in your neighbourhood.</p></div><button className="button-primary" onClick={() => setCreating(true)}><Plus />Report an issue</button></header>{message && <p className="notice">{message}</p>}{creating && <form className="report-form" onSubmit={create}><h2>Report an issue</h2><label>Issue title<input name="title" placeholder="For example, missed collection" required /></label><label>What happened?<textarea name="description" rows={4} placeholder="Describe the issue clearly" required /></label><label>Category<input name="category" placeholder="For example, collection" required /></label><label className="photo-input"><Camera />Add a photo<input name="image" type="file" accept="image/*" required /></label><div><button className="button-secondary" type="button" onClick={() => setCreating(false)}>Cancel</button><button className="button-primary" disabled={loading}>{loading ? "Submitting..." : <><Send />Submit report</>}</button></div></form>}<section className="report-list">{reports.length ? reports.map(report => <article key={report.id}><span><CircleAlert /></span><div><b className={`report-status ${report.status.toLowerCase()}`}>{report.status.replaceAll("_", " ")}</b><h2>{report.title}</h2><p>{report.description}</p><small>{report.location || profile?.ward || "Your neighbourhood"} · {formatDate(report.createdAt)}</small></div>{report.imagePath && <img src={`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080"}/uploads/${encodeURIComponent(report.imagePath)}`} alt="Reported issue" />}</article>) : <div className="empty-reports"><CircleAlert /><h2>No reports yet</h2><p>Use “Report an issue” when something needs attention.</p></div>}</section></main>;
}
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "Recently added"; }
