spring.application.name=CivicMitra
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/civicmitra}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.security.user.name=deep
#spring.security.user.password=deep
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG
# AI provider configuration
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai

spring.ai.openai.chat.options.model=meta-llama/llama-4-scout-17b-16e-instruct

#  Adjust timeout if Groq is slow with large images
spring.mvc.async.request-timeout=60000
